// Generated by ts-to-zod
import { z } from "zod";

export const pointSchema = z.tuple([
  z.number(),
  z.number(),
  z.number(),
  z.number(),
  z.number(),
]);

export const routeSchema = z.object({
  route: z.array(pointSchema),
});
